### ISSUE TITLE
Compendium browser console errors "decoratedItem.properties is not iterable" on 2.2.0

### ISSUE THREAD

**Issue by modzy2** [League-of-Foundry-Developers/compendium-browser#63]
After update to 2.2.0, I am getting this on the console, and the compendium browser remains "Loading..." and does not complete

`compendium-browser.js:450 Uncaught (in promise) TypeError: decoratedItem.properties is not iterable
    at CompendiumBrowser.<anonymous> (compendium-browser.js:450:43)
    at Array.reduce (<anonymous>)
    at compendium-browser.js:425:16
    at async CompendiumBrowser.loadAndFilterItems (compendium-browser.js:423:6)
    at async CompendiumBrowser.renderItemData (compendium-browser.js:776:16)
    at async CompendiumBrowser.replaceList (compendium-browser.js:741:26)
(anonymous) @ compendium-browser.js:450
(anonymous) @ compendium-browser.js:425
await in (anonymous) (async)
afterRender @ compendium-browser.js:689
#call @ foundry.js:730
callAll @ foundry.js:687
_render @ foundry.js:5855
await in _render (async)
render @ foundry.js:5769
(anonymous) @ compendium-browser.js:676
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2`

I went back to 2.1.0 and it's ok.

**Comment by modzy2** [comment]
[console_log.txt](https://github.com/League-of-Foundry-Developers/compendium-browser/files/14171702/console_log.txt)

**Comment by mclemente** [comment]
The project has been moved to https://github.com/mclemente/compendium-browser. I forgot to change the package URL on the Foundry page.

About the issue, I couldn't replicate it. If you hadn't updated to dnd5e 3.0, you shouldn't have updated the module anyway.
